[package]
name = "pi_animation"
version = "0.0.1"
authors = ["baip0002 <bai9253461@gmail.com>"]
edition = "2021"
description = "Animation Runtime Library"
# repository = "https://github.com/GaiaWorld/pi_animation_ecs"
license = "MIT OR Apache-2.0"
keywords = ["pi", "animation"]

[dependencies]
num-traits = "0.2"
nalgebra = "0.31.1"
pi_share = "0.2.0"
pi_map = "0.1.0"
pi_atom = "0.2.0"
pi_ecs = "0.1.0"
pi_hash = "0.1.1"
pi_time = "0.1.0"
pi_local_timer = "0.1.0"
pi_counter = {path="../pi_counter"}
delay_clock = {path="../delay_clock"}
pi_curves = {path="../pi_curves"}
log = "0.4.16"
env_logger = "0.9.0"